[project]
name = "ecomm-prod-assisstant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain==0.3.27",
    "langchain-core==0.3.75",
    "python-dotenv==1.1.1",
]
