apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-assisstant
  labels:
    app: product-assisstant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-assisstant
  template:
    metadata:
      labels:
        app: product-assisstant
    spec:
      containers:
        - name: product-assisstant
          image: 928784197796.dkr.ecr.us-east-1.amazonaws.com/product-assisstant:latest
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 8000
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: product-assisstant-secrets
                  key: GOOGLE_API_KEY
            - name: ASTRA_DB_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: product-assisstant-secrets
                  key: ASTRA_DB_API_ENDPOINT
            - name: ASTRA_DB_APPLICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: product-assisstant-secrets
                  key: ASTRA_DB_APPLICATION_TOKEN
            - name: ASTRA_DB_KEYSPACE
              valueFrom:
                secretKeyRef:
                  name: product-assisstant-secrets
                  key: ASTRA_DB_KEYSPACE
