apiVersion: v1
kind: Service
metadata:
  name: product-assisstant-service
spec:
  type: LoadBalancer
  selector:
    app: product-assisstant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000